export type DeleteAction = "cascade" | "no action" | "restrict" | "set null";

export interface WorkspaceRelationship {
  readonly key: string;
  readonly childTable: string;
  readonly parentTable: string;
  readonly childForeignColumn: string;
  readonly childWorkspaceColumn: "workspace_id";
  readonly parentIdColumn: "id";
  readonly parentWorkspaceColumn: "workspace_id";
  readonly nullable: boolean;
  readonly onDelete: DeleteAction;
  readonly onUpdate: "no action";
  readonly currentForeignKeyName: string;
  readonly compositeForeignKeyName: string;
  readonly parentUniqueConstraintName: string;
  readonly drizzleManaged: boolean;
  readonly confirmedByB3: boolean;
  readonly previouslyProtectedByTrigger: boolean;
}

type RelationshipInput = Omit<
  WorkspaceRelationship,
  | "key"
  | "childWorkspaceColumn"
  | "parentIdColumn"
  | "parentWorkspaceColumn"
  | "onUpdate"
  | "currentForeignKeyName"
  | "parentUniqueConstraintName"
>;

function relationship(input: RelationshipInput): WorkspaceRelationship {
  return {
    ...input,
    key: `${input.childTable}.${input.childForeignColumn}->${input.parentTable}.id`,
    childWorkspaceColumn: "workspace_id",
    parentIdColumn: "id",
    parentWorkspaceColumn: "workspace_id",
    onUpdate: "no action",
    currentForeignKeyName: `${input.childTable}_${input.childForeignColumn}_${input.parentTable}_id_fk`,
    parentUniqueConstraintName: `${input.parentTable}_workspace_id_id_uq`,
  };
}

/**
 * The approved B3.2 target: every direct relationship whose child and parent
 * both carry workspace_id. Keep this table aligned with the canonical catalog.
 */
export const WORKSPACE_RELATIONSHIPS = [
  relationship({
    childTable: "bookings",
    parentTable: "customers",
    childForeignColumn: "customer_id",
    nullable: false,
    onDelete: "cascade",
    compositeForeignKeyName: "bookings_customer_workspace_fk",
    drizzleManaged: true,
    confirmedByB3: true,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "bookings",
    parentTable: "services",
    childForeignColumn: "service_id",
    nullable: false,
    onDelete: "no action",
    compositeForeignKeyName: "bookings_service_workspace_fk",
    drizzleManaged: true,
    confirmedByB3: true,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "bookings",
    parentTable: "team_members",
    childForeignColumn: "staff_id",
    nullable: true,
    onDelete: "set null",
    compositeForeignKeyName: "bookings_staff_workspace_fk",
    drizzleManaged: false,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "buildings",
    parentTable: "properties",
    childForeignColumn: "property_id",
    nullable: false,
    onDelete: "restrict",
    compositeForeignKeyName: "buildings_property_workspace_fk",
    drizzleManaged: true,
    confirmedByB3: true,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "crm_activities",
    parentTable: "crm_opportunities",
    childForeignColumn: "opportunity_id",
    nullable: false,
    onDelete: "cascade",
    compositeForeignKeyName: "crm_activities_opportunity_workspace_fk",
    drizzleManaged: true,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "crm_opportunities",
    parentTable: "customers",
    childForeignColumn: "customer_id",
    nullable: true,
    onDelete: "set null",
    compositeForeignKeyName: "crm_opportunities_customer_workspace_fk",
    drizzleManaged: false,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "crm_opportunities",
    parentTable: "leads",
    childForeignColumn: "lead_id",
    nullable: true,
    onDelete: "set null",
    compositeForeignKeyName: "crm_opportunities_lead_workspace_fk",
    drizzleManaged: false,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "crm_opportunities",
    parentTable: "crm_pipelines",
    childForeignColumn: "pipeline_id",
    nullable: false,
    onDelete: "cascade",
    compositeForeignKeyName: "crm_opportunities_pipeline_workspace_fk",
    drizzleManaged: true,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "crm_opportunities",
    parentTable: "crm_stages",
    childForeignColumn: "stage_id",
    nullable: false,
    onDelete: "restrict",
    compositeForeignKeyName: "crm_opportunities_stage_workspace_fk",
    drizzleManaged: true,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "crm_stages",
    parentTable: "crm_pipelines",
    childForeignColumn: "pipeline_id",
    nullable: false,
    onDelete: "cascade",
    compositeForeignKeyName: "crm_stages_pipeline_workspace_fk",
    drizzleManaged: true,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "housekeeping_tasks",
    parentTable: "team_members",
    childForeignColumn: "assigned_to",
    nullable: true,
    onDelete: "set null",
    compositeForeignKeyName: "housekeeping_assigned_to_workspace_fk",
    drizzleManaged: false,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "housekeeping_tasks",
    parentTable: "buildings",
    childForeignColumn: "building_id",
    nullable: false,
    onDelete: "restrict",
    compositeForeignKeyName: "housekeeping_building_workspace_fk",
    drizzleManaged: true,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "housekeeping_tasks",
    parentTable: "team_members",
    childForeignColumn: "completed_by",
    nullable: true,
    onDelete: "set null",
    compositeForeignKeyName: "housekeeping_completed_by_workspace_fk",
    drizzleManaged: false,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "housekeeping_tasks",
    parentTable: "team_members",
    childForeignColumn: "created_by",
    nullable: true,
    onDelete: "set null",
    compositeForeignKeyName: "housekeeping_created_by_workspace_fk",
    drizzleManaged: false,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "housekeeping_tasks",
    parentTable: "properties",
    childForeignColumn: "property_id",
    nullable: false,
    onDelete: "restrict",
    compositeForeignKeyName: "housekeeping_property_workspace_fk",
    drizzleManaged: true,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "housekeeping_tasks",
    parentTable: "reservations",
    childForeignColumn: "reservation_id",
    nullable: true,
    onDelete: "restrict",
    compositeForeignKeyName: "housekeeping_reservation_workspace_fk",
    drizzleManaged: true,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "housekeeping_tasks",
    parentTable: "rental_units",
    childForeignColumn: "unit_id",
    nullable: false,
    onDelete: "restrict",
    compositeForeignKeyName: "housekeeping_unit_workspace_fk",
    drizzleManaged: true,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "invoice_line_items",
    parentTable: "invoices",
    childForeignColumn: "invoice_id",
    nullable: false,
    onDelete: "cascade",
    compositeForeignKeyName: "invoice_line_items_invoice_workspace_fk",
    drizzleManaged: true,
    confirmedByB3: false,
    previouslyProtectedByTrigger: true,
  }),
  relationship({
    childTable: "invoices",
    parentTable: "customers",
    childForeignColumn: "customer_id",
    nullable: true,
    onDelete: "set null",
    compositeForeignKeyName: "invoices_customer_workspace_fk",
    drizzleManaged: false,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "invoices",
    parentTable: "reservations",
    childForeignColumn: "reservation_id",
    nullable: true,
    onDelete: "restrict",
    compositeForeignKeyName: "invoices_reservation_workspace_fk",
    drizzleManaged: false,
    confirmedByB3: false,
    previouslyProtectedByTrigger: true,
  }),
  relationship({
    childTable: "invoices",
    parentTable: "team_members",
    childForeignColumn: "voided_by",
    nullable: true,
    onDelete: "set null",
    compositeForeignKeyName: "invoices_voided_by_workspace_fk",
    drizzleManaged: false,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "invoices",
    parentTable: "team_members",
    childForeignColumn: "written_off_by",
    nullable: true,
    onDelete: "set null",
    compositeForeignKeyName: "invoices_written_off_by_workspace_fk",
    drizzleManaged: false,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "leads",
    parentTable: "customers",
    childForeignColumn: "converted_customer_id",
    nullable: true,
    onDelete: "set null",
    compositeForeignKeyName: "leads_converted_customer_workspace_fk",
    drizzleManaged: false,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "leads",
    parentTable: "sites",
    childForeignColumn: "site_id",
    nullable: false,
    onDelete: "cascade",
    compositeForeignKeyName: "leads_site_workspace_fk",
    drizzleManaged: true,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "page_sections",
    parentTable: "pages",
    childForeignColumn: "page_id",
    nullable: false,
    onDelete: "cascade",
    compositeForeignKeyName: "page_sections_page_workspace_fk",
    drizzleManaged: true,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "page_sections",
    parentTable: "sites",
    childForeignColumn: "site_id",
    nullable: false,
    onDelete: "cascade",
    compositeForeignKeyName: "page_sections_site_workspace_fk",
    drizzleManaged: true,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "pages",
    parentTable: "sites",
    childForeignColumn: "site_id",
    nullable: false,
    onDelete: "cascade",
    compositeForeignKeyName: "pages_site_workspace_fk",
    drizzleManaged: true,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "payments",
    parentTable: "team_members",
    childForeignColumn: "actor_team_member_id",
    nullable: true,
    onDelete: "set null",
    compositeForeignKeyName: "payments_actor_member_workspace_fk",
    drizzleManaged: false,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "payments",
    parentTable: "bookings",
    childForeignColumn: "booking_id",
    nullable: true,
    onDelete: "set null",
    compositeForeignKeyName: "payments_booking_workspace_fk",
    drizzleManaged: false,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "payments",
    parentTable: "customers",
    childForeignColumn: "customer_id",
    nullable: true,
    onDelete: "set null",
    compositeForeignKeyName: "payments_customer_workspace_fk",
    drizzleManaged: false,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "payments",
    parentTable: "invoices",
    childForeignColumn: "invoice_id",
    nullable: true,
    onDelete: "set null",
    compositeForeignKeyName: "payments_invoice_workspace_fk",
    drizzleManaged: false,
    confirmedByB3: false,
    previouslyProtectedByTrigger: true,
  }),
  relationship({
    childTable: "payments",
    parentTable: "payments",
    childForeignColumn: "refunded_payment_id",
    nullable: true,
    onDelete: "restrict",
    compositeForeignKeyName: "payments_refunded_payment_workspace_fk",
    drizzleManaged: false,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "rental_units",
    parentTable: "buildings",
    childForeignColumn: "building_id",
    nullable: false,
    onDelete: "restrict",
    compositeForeignKeyName: "rental_units_building_workspace_fk",
    drizzleManaged: true,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "rental_units",
    parentTable: "properties",
    childForeignColumn: "property_id",
    nullable: false,
    onDelete: "restrict",
    compositeForeignKeyName: "rental_units_property_workspace_fk",
    drizzleManaged: true,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "reservations",
    parentTable: "customers",
    childForeignColumn: "customer_id",
    nullable: false,
    onDelete: "cascade",
    compositeForeignKeyName: "reservations_customer_workspace_fk",
    drizzleManaged: true,
    confirmedByB3: true,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "reservations",
    parentTable: "team_members",
    childForeignColumn: "staff_id",
    nullable: true,
    onDelete: "set null",
    compositeForeignKeyName: "reservations_staff_workspace_fk",
    drizzleManaged: false,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "reservations",
    parentTable: "rental_units",
    childForeignColumn: "unit_id",
    nullable: false,
    onDelete: "restrict",
    compositeForeignKeyName: "reservations_unit_workspace_fk",
    drizzleManaged: true,
    confirmedByB3: true,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "site_domains",
    parentTable: "sites",
    childForeignColumn: "site_id",
    nullable: false,
    onDelete: "cascade",
    compositeForeignKeyName: "site_domains_site_workspace_fk",
    drizzleManaged: true,
    confirmedByB3: true,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "site_versions",
    parentTable: "sites",
    childForeignColumn: "site_id",
    nullable: false,
    onDelete: "cascade",
    compositeForeignKeyName: "site_versions_site_workspace_fk",
    drizzleManaged: true,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
  relationship({
    childTable: "sites",
    parentTable: "site_versions",
    childForeignColumn: "published_version_id",
    nullable: true,
    onDelete: "set null",
    compositeForeignKeyName: "sites_published_version_workspace_fk",
    drizzleManaged: false,
    confirmedByB3: false,
    previouslyProtectedByTrigger: false,
  }),
] as const satisfies readonly WorkspaceRelationship[];

export const PARENT_WORKSPACE_UNIQUE_CONSTRAINTS = [
  "bookings",
  "buildings",
  "crm_opportunities",
  "crm_pipelines",
  "crm_stages",
  "customers",
  "invoices",
  "leads",
  "pages",
  "payments",
  "properties",
  "rental_units",
  "reservations",
  "services",
  "site_versions",
  "sites",
  "team_members",
] as const;
