import { TeamIcon } from "../icons";
import { UserPlusIcon } from "../home/icons";
import type { SelectOption } from "../business-profile/types";
import { RepeatIcon, StarIcon } from "./icons";
import type { CrmStat, Customer } from "./types";

/* All CRM data is mock (Bloom Studio, a salon). Kept in this file so a real
   API response can be dropped in without touching any component. */

export const TAGS = ["Color", "Regular", "Referral", "Nails", "Bridal", "Membership"];

export const CUSTOMERS: Customer[] = [
  {
    id: "CU-2001",
    name: "Amelia Chen",
    email: "amelia.chen@email.com",
    phone: "+1 (415) 555-0111",
    initials: "AC",
    color: "#6d5ef9",
    status: "VIP",
    tags: ["Color", "Membership"],
    lastVisit: "Jul 6, 2026",
    lastVisitDays: 2,
    totalSpent: "$3,240",
    lifetimeValue: "$3,240",
    visits: 18,
    since: "Mar 2024",
    notes: "Prefers warm balayage tones. Always books with Ava. Allergic to ammonia.",
    upcoming: { service: "Balayage & Cut", date: "Jul 15, 2026", time: "9:00 AM", staff: "Ava Thompson" },
    history: [
      { id: "b1", service: "Balayage & Cut", date: "Jul 6, 2026", price: "$180" },
      { id: "b2", service: "Gloss Treatment", date: "Jun 10, 2026", price: "$70" },
      { id: "b3", service: "Balayage & Cut", date: "May 8, 2026", price: "$180" },
    ],
  },
  {
    id: "CU-2002",
    name: "Marcus Reid",
    email: "marcus.reid@email.com",
    phone: "+1 (415) 555-0132",
    initials: "MR",
    color: "#2dd4bf",
    status: "Active",
    tags: ["Regular"],
    lastVisit: "Jul 4, 2026",
    lastVisitDays: 4,
    totalSpent: "$620",
    lifetimeValue: "$620",
    visits: 14,
    since: "Jan 2025",
    notes: "Monthly beard trim. Prefers Diego.",
    upcoming: { service: "Beard Trim", date: "Aug 1, 2026", time: "10:15 AM", staff: "Diego Martinez" },
    history: [
      { id: "b1", service: "Beard Trim", date: "Jul 4, 2026", price: "$35" },
      { id: "b2", service: "Beard Trim", date: "Jun 3, 2026", price: "$35" },
    ],
  },
  {
    id: "CU-2003",
    name: "Sofia Marino",
    email: "sofia.marino@email.com",
    phone: "+1 (415) 555-0148",
    initials: "SM",
    color: "#f59e0b",
    status: "New",
    tags: ["Nails", "Referral"],
    lastVisit: "Jul 8, 2026",
    lastVisitDays: 0,
    totalSpent: "$45",
    lifetimeValue: "$45",
    visits: 1,
    since: "Jul 2026",
    notes: "Referred by Amelia Chen. First gel manicure — loved it.",
    upcoming: null,
    history: [{ id: "b1", service: "Gel Manicure", date: "Jul 8, 2026", price: "$45" }],
  },
  {
    id: "CU-2004",
    name: "Priya Anand",
    email: "priya.anand@email.com",
    phone: "+1 (415) 555-0170",
    initials: "PA",
    color: "#ec4899",
    status: "VIP",
    tags: ["Color", "Bridal"],
    lastVisit: "Jun 28, 2026",
    lastVisitDays: 10,
    totalSpent: "$2,860",
    lifetimeValue: "$2,860",
    visits: 15,
    since: "Aug 2024",
    notes: "Booking a bridal package for September. Wants a trial run first.",
    upcoming: { service: "Color & Cut", date: "Jul 20, 2026", time: "1:30 PM", staff: "Ava Thompson" },
    history: [
      { id: "b1", service: "Color & Cut", date: "Jun 28, 2026", price: "$150" },
      { id: "b2", service: "Bridal Trial", date: "Jun 1, 2026", price: "$220" },
    ],
  },
  {
    id: "CU-2005",
    name: "Elena Novak",
    email: "elena.novak@email.com",
    phone: "+1 (415) 555-0199",
    initials: "EN",
    color: "#38bdf8",
    status: "Active",
    tags: ["Regular", "Color"],
    lastVisit: "Jun 20, 2026",
    lastVisitDays: 18,
    totalSpent: "$980",
    lifetimeValue: "$980",
    visits: 9,
    since: "Nov 2024",
    notes: "Books blowouts before events. Flexible on stylist.",
    upcoming: null,
    history: [
      { id: "b1", service: "Blowout", date: "Jun 20, 2026", price: "$55" },
      { id: "b2", service: "Color & Cut", date: "May 12, 2026", price: "$150" },
    ],
  },
  {
    id: "CU-2006",
    name: "James Okafor",
    email: "james.okafor@email.com",
    phone: "+1 (415) 555-0123",
    initials: "JO",
    color: "#a78bfa",
    status: "Active",
    tags: ["Membership"],
    lastVisit: "Jun 12, 2026",
    lastVisitDays: 26,
    totalSpent: "$1,120",
    lifetimeValue: "$1,120",
    visits: 11,
    since: "Feb 2025",
    notes: "Scalp treatment plan — follow up every 4 weeks.",
    upcoming: { service: "Scalp Treatment", date: "Jul 18, 2026", time: "2:00 PM", staff: "Mia Chen" },
    history: [{ id: "b1", service: "Scalp Treatment", date: "Jun 12, 2026", price: "$90" }],
  },
  {
    id: "CU-2007",
    name: "Hannah Berg",
    email: "hannah.berg@email.com",
    phone: "+1 (415) 555-0155",
    initials: "HB",
    color: "#34d399",
    status: "Active",
    tags: ["Color", "Regular"],
    lastVisit: "Jun 6, 2026",
    lastVisitDays: 32,
    totalSpent: "$1,540",
    lifetimeValue: "$1,540",
    visits: 12,
    since: "Sep 2024",
    notes: "Rebooks on the spot. Loyal to Ava.",
    upcoming: null,
    history: [{ id: "b1", service: "Balayage & Cut", date: "Jun 6, 2026", price: "$180" }],
  },
  {
    id: "CU-2008",
    name: "Liam Foster",
    email: "liam.foster@email.com",
    phone: "+1 (415) 555-0161",
    initials: "LF",
    color: "#fb7185",
    status: "Inactive",
    tags: ["Referral"],
    lastVisit: "Feb 14, 2026",
    lastVisitDays: 144,
    totalSpent: "$210",
    lifetimeValue: "$210",
    visits: 4,
    since: "Oct 2025",
    notes: "Hasn't returned since February — good candidate for a win-back offer.",
    upcoming: null,
    history: [{ id: "b1", service: "Beard Trim", date: "Feb 14, 2026", price: "$35" }],
  },
  {
    id: "CU-2009",
    name: "Grace Kim",
    email: "grace.kim@email.com",
    phone: "+1 (415) 555-0184",
    initials: "GK",
    color: "#facc15",
    status: "New",
    tags: ["Nails", "Bridal"],
    lastVisit: "Jul 7, 2026",
    lastVisitDays: 1,
    totalSpent: "$90",
    lifetimeValue: "$90",
    visits: 2,
    since: "Jun 2026",
    notes: "Wedding in August. Interested in a nails + hair package.",
    upcoming: { service: "Gel Manicure", date: "Jul 10, 2026", time: "12:00 PM", staff: "Mia Chen" },
    history: [
      { id: "b1", service: "Gel Manicure", date: "Jul 7, 2026", price: "$45" },
      { id: "b2", service: "Gel Manicure", date: "Jun 24, 2026", price: "$45" },
    ],
  },
];

export const STATS: CrmStat[] = [
  { id: "total", label: "Total customers", value: "1,204", icon: TeamIcon },
  { id: "new", label: "New this month", value: "48", icon: UserPlusIcon },
  { id: "returning", label: "Returning", value: "71%", icon: RepeatIcon },
  { id: "vip", label: "VIP customers", value: "36", icon: StarIcon },
];

const toOptions = (values: string[]): SelectOption[] =>
  values.map((value) => ({ value, label: value }));

export const STATUS_OPTIONS: SelectOption[] = [
  { value: "all", label: "All statuses" },
  ...toOptions(["Active", "New", "VIP", "Inactive"]),
];

export const TAG_OPTIONS: SelectOption[] = [
  { value: "all", label: "All tags" },
  ...toOptions(TAGS),
];

export const LAST_VISIT_OPTIONS: SelectOption[] = [
  { value: "all", label: "Any time" },
  { value: "7", label: "Last 7 days" },
  { value: "30", label: "Last 30 days" },
  { value: "90", label: "Last 90 days" },
];
